import { defineField, defineType } from "sanity";

export const car = defineType({
  name: "car",
  title: "Car",
  type: "document",
  groups: [
    { name: "basic", title: "Basic Info", default: true },
    { name: "pricing", title: "Pricing" },
    { name: "description", title: "Description & Features" },
    { name: "powertrain", title: "Powertrain" },
    { name: "appearance", title: "Appearance & Media" },
    { name: "registration", title: "Registration & Documents" },
    { name: "dimensions", title: "Dimensions" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Name (English)",
      type: "string",
      group: "basic",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "nameJa",
      title: "Name (Japanese)",
      type: "string",
      group: "basic",
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "basic",
      options: { source: "name", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "stockNo",
      title: "Stock No.",
      type: "string",
      group: "basic",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "make",
      title: "Make",
      type: "string",
      group: "basic",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "model",
      title: "Model",
      type: "string",
      group: "basic",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "grade",
      title: "Grade",
      type: "string",
      group: "basic",
    }),
    defineField({
      name: "vehicleType",
      title: "Type / Generation",
      type: "string",
      group: "basic",
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "number",
      group: "basic",
      validation: (rule) => rule.required().min(1900).max(2100),
    }),
    defineField({
      name: "mileage",
      title: "Mileage (km)",
      type: "number",
      group: "basic",
    }),
    defineField({
      name: "featured",
      title: "Featured on homepage",
      type: "boolean",
      group: "basic",
      initialValue: false,
    }),
    defineField({
      name: "price",
      title: "Price (USD)",
      type: "number",
      group: "pricing",
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: "description",
      title: "Description (English)",
      type: "text",
      rows: 4,
      group: "description",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "descriptionJa",
      title: "Description (Japanese)",
      type: "text",
      rows: 4,
      group: "description",
    }),
    defineField({
      name: "features",
      title: "Features (English)",
      type: "array",
      group: "description",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "featuresJa",
      title: "Features (Japanese)",
      type: "array",
      group: "description",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "fuelType",
      title: "Fuel Type (English)",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "fuelTypeJa",
      title: "Fuel Type (Japanese)",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "transmission",
      title: "Transmission (English)",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "transmissionJa",
      title: "Transmission (Japanese)",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "engine",
      title: "Engine (English)",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "engineJa",
      title: "Engine (Japanese)",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "displacement",
      title: "Displacement",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "engineType",
      title: "Engine Type",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "turbo",
      title: "Turbo",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "shift",
      title: "Shift",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "driveSystem",
      title: "Drive System",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "capacity",
      title: "Seating Capacity",
      type: "string",
      group: "powertrain",
    }),
    defineField({
      name: "color",
      title: "Color (English)",
      type: "string",
      group: "appearance",
    }),
    defineField({
      name: "colorJa",
      title: "Color (Japanese)",
      type: "string",
      group: "appearance",
    }),
    defineField({
      name: "images",
      title: "Photos",
      type: "array",
      group: "appearance",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({
              name: "alt",
              title: "Alt text",
              type: "string",
            }),
          ],
        },
      ],
      description: "Upload multiple photos — the first image is used as the cover.",
    }),
    defineField({
      name: "registrationYear",
      title: "Registration Year",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "place",
      title: "Location / Yard",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "designationTypeNo",
      title: "Designation Type No.",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "classificationNo",
      title: "Classification No.",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "chassisNo",
      title: "Chassis No.",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "steeringWheel",
      title: "Steering Wheel",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "inspectionInfo",
      title: "Inspection Info",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "recyclingTicket",
      title: "Recycling Ticket",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "documentsDelivery",
      title: "Documents Delivery",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "length",
      title: "Length",
      type: "string",
      group: "dimensions",
    }),
    defineField({
      name: "width",
      title: "Width",
      type: "string",
      group: "dimensions",
    }),
    defineField({
      name: "height",
      title: "Height",
      type: "string",
      group: "dimensions",
    }),
    defineField({
      name: "vehicleWeight",
      title: "Vehicle Weight",
      type: "string",
      group: "dimensions",
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "stockNo",
      media: "images.0",
    },
  },
});
